// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

/*
Package registry is a generated protocol buffer package.

It is generated from these files:
	registry.proto

It has these top-level messages:
	DeviceAddRequest
	DeviceAddResponse
*/
package registry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceAddRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeviceAddRequest) Reset()                    { *m = DeviceAddRequest{} }
func (m *DeviceAddRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceAddRequest) ProtoMessage()               {}
func (*DeviceAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeviceAddResponse struct {
	Reply string `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`
}

func (m *DeviceAddResponse) Reset()                    { *m = DeviceAddResponse{} }
func (m *DeviceAddResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceAddResponse) ProtoMessage()               {}
func (*DeviceAddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceAddResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceAddRequest)(nil), "registry.DeviceAddRequest")
	proto.RegisterType((*DeviceAddResponse)(nil), "registry.DeviceAddResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Registry service

type RegistryClient interface {
	// Add a device to registry
	AddDevice(ctx context.Context, in *DeviceAddRequest, opts ...grpc.CallOption) (*DeviceAddResponse, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) AddDevice(ctx context.Context, in *DeviceAddRequest, opts ...grpc.CallOption) (*DeviceAddResponse, error) {
	out := new(DeviceAddResponse)
	err := grpc.Invoke(ctx, "/registry.Registry/AddDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Registry service

type RegistryServer interface {
	// Add a device to registry
	AddDevice(context.Context, *DeviceAddRequest) (*DeviceAddResponse, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/AddDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).AddDevice(ctx, req.(*DeviceAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "registry.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDevice",
			Handler:    _Registry_AddDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xd4,
	0xb8, 0x04, 0x5c, 0x52, 0xcb, 0x32, 0x93, 0x53, 0x1d, 0x53, 0x52, 0x82, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x25, 0x4d, 0x2e, 0x41, 0x24, 0x75, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0x22, 0x5c, 0xac, 0x45, 0xa9, 0x05, 0x39, 0x95, 0x50, 0x95, 0x10, 0x8e, 0x51, 0x10, 0x17, 0x47,
	0x10, 0xd4, 0x78, 0x21, 0x37, 0x2e, 0x4e, 0xc7, 0x94, 0x14, 0x88, 0x4e, 0x21, 0x29, 0x3d, 0xb8,
	0x33, 0xd0, 0xed, 0x94, 0x92, 0xc6, 0x2a, 0x07, 0xb1, 0x47, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x6e,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0x16, 0x1c, 0x1e, 0xc9, 0x00, 0x00, 0x00,
}
