// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	VersionRequest
	VersionReply
	BrokerRequest
	BrokerReply
	ClientsRequest
	ClientsReply
	ClientInfo
	AdminsRequest
	AdminsReply
	ClusterRequest
	ClusterReply
	RoutesRequest
	RoutesReply
	StatusRequest
	StatusReply
	PluginsRequest
	PluginsReply
	ServicesRequest
	ServicesReply
	SubscriptionsRequest
	SubscriptionsReply
	SessionsRequest
	SessionsReply
	TopicsRequest
	TopicsReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Version
type VersionRequest struct {
}

func (m *VersionRequest) Reset()                    { *m = VersionRequest{} }
func (m *VersionRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()               {}
func (*VersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VersionReply struct {
	Version string `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *VersionReply) Reset()                    { *m = VersionReply{} }
func (m *VersionReply) String() string            { return proto.CompactTextString(m) }
func (*VersionReply) ProtoMessage()               {}
func (*VersionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Broker
type BrokerRequest struct {
	Category string `protobuf:"bytes,1,opt,name=Category" json:"Category,omitempty"`
}

func (m *BrokerRequest) Reset()                    { *m = BrokerRequest{} }
func (m *BrokerRequest) String() string            { return proto.CompactTextString(m) }
func (*BrokerRequest) ProtoMessage()               {}
func (*BrokerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BrokerRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type BrokerReply struct {
	Stats   map[string]uint64 `protobuf:"bytes,1,rep,name=Stats" json:"Stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Metrics map[string]uint64 `protobuf:"bytes,2,rep,name=Metrics" json:"Metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *BrokerReply) Reset()                    { *m = BrokerReply{} }
func (m *BrokerReply) String() string            { return proto.CompactTextString(m) }
func (*BrokerReply) ProtoMessage()               {}
func (*BrokerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BrokerReply) GetStats() map[string]uint64 {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *BrokerReply) GetMetrics() map[string]uint64 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

// Clients
type ClientsRequest struct {
	Category string `protobuf:"bytes,1,opt,name=Category" json:"Category,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=ClientId" json:"ClientId,omitempty"`
}

func (m *ClientsRequest) Reset()                    { *m = ClientsRequest{} }
func (m *ClientsRequest) String() string            { return proto.CompactTextString(m) }
func (*ClientsRequest) ProtoMessage()               {}
func (*ClientsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClientsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ClientsRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type ClientsReply struct {
	Result  bool          `protobuf:"varint,1,opt,name=Result" json:"Result,omitempty"`
	Clients []*ClientInfo `protobuf:"bytes,2,rep,name=Clients" json:"Clients,omitempty"`
}

func (m *ClientsReply) Reset()                    { *m = ClientsReply{} }
func (m *ClientsReply) String() string            { return proto.CompactTextString(m) }
func (*ClientsReply) ProtoMessage()               {}
func (*ClientsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ClientsReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *ClientsReply) GetClients() []*ClientInfo {
	if m != nil {
		return m.Clients
	}
	return nil
}

type ClientInfo struct {
	UserName     string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	CleanSession bool   `protobuf:"varint,2,opt,name=CleanSession" json:"CleanSession,omitempty"`
	PeerName     string `protobuf:"bytes,3,opt,name=PeerName" json:"PeerName,omitempty"`
	ConnectTime  string `protobuf:"bytes,4,opt,name=ConnectTime" json:"ConnectTime,omitempty"`
}

func (m *ClientInfo) Reset()                    { *m = ClientInfo{} }
func (m *ClientInfo) String() string            { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()               {}
func (*ClientInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClientInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ClientInfo) GetCleanSession() bool {
	if m != nil {
		return m.CleanSession
	}
	return false
}

func (m *ClientInfo) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

func (m *ClientInfo) GetConnectTime() string {
	if m != nil {
		return m.ConnectTime
	}
	return ""
}

type AdminsRequest struct {
}

func (m *AdminsRequest) Reset()                    { *m = AdminsRequest{} }
func (m *AdminsRequest) String() string            { return proto.CompactTextString(m) }
func (*AdminsRequest) ProtoMessage()               {}
func (*AdminsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AdminsReply struct {
}

func (m *AdminsReply) Reset()                    { *m = AdminsReply{} }
func (m *AdminsReply) String() string            { return proto.CompactTextString(m) }
func (*AdminsReply) ProtoMessage()               {}
func (*AdminsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ClusterRequest struct {
}

func (m *ClusterRequest) Reset()                    { *m = ClusterRequest{} }
func (m *ClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterRequest) ProtoMessage()               {}
func (*ClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ClusterReply struct {
}

func (m *ClusterReply) Reset()                    { *m = ClusterReply{} }
func (m *ClusterReply) String() string            { return proto.CompactTextString(m) }
func (*ClusterReply) ProtoMessage()               {}
func (*ClusterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type RoutesRequest struct {
}

func (m *RoutesRequest) Reset()                    { *m = RoutesRequest{} }
func (m *RoutesRequest) String() string            { return proto.CompactTextString(m) }
func (*RoutesRequest) ProtoMessage()               {}
func (*RoutesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type RoutesReply struct {
}

func (m *RoutesReply) Reset()                    { *m = RoutesReply{} }
func (m *RoutesReply) String() string            { return proto.CompactTextString(m) }
func (*RoutesReply) ProtoMessage()               {}
func (*RoutesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type StatusReply struct {
}

func (m *StatusReply) Reset()                    { *m = StatusReply{} }
func (m *StatusReply) String() string            { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()               {}
func (*StatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type PluginsRequest struct {
}

func (m *PluginsRequest) Reset()                    { *m = PluginsRequest{} }
func (m *PluginsRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginsRequest) ProtoMessage()               {}
func (*PluginsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type PluginsReply struct {
}

func (m *PluginsReply) Reset()                    { *m = PluginsReply{} }
func (m *PluginsReply) String() string            { return proto.CompactTextString(m) }
func (*PluginsReply) ProtoMessage()               {}
func (*PluginsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ServicesRequest struct {
}

func (m *ServicesRequest) Reset()                    { *m = ServicesRequest{} }
func (m *ServicesRequest) String() string            { return proto.CompactTextString(m) }
func (*ServicesRequest) ProtoMessage()               {}
func (*ServicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type ServicesReply struct {
}

func (m *ServicesReply) Reset()                    { *m = ServicesReply{} }
func (m *ServicesReply) String() string            { return proto.CompactTextString(m) }
func (*ServicesReply) ProtoMessage()               {}
func (*ServicesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type SubscriptionsRequest struct {
}

func (m *SubscriptionsRequest) Reset()                    { *m = SubscriptionsRequest{} }
func (m *SubscriptionsRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsRequest) ProtoMessage()               {}
func (*SubscriptionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type SubscriptionsReply struct {
}

func (m *SubscriptionsReply) Reset()                    { *m = SubscriptionsReply{} }
func (m *SubscriptionsReply) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsReply) ProtoMessage()               {}
func (*SubscriptionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type SessionsRequest struct {
}

func (m *SessionsRequest) Reset()                    { *m = SessionsRequest{} }
func (m *SessionsRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionsRequest) ProtoMessage()               {}
func (*SessionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type SessionsReply struct {
}

func (m *SessionsReply) Reset()                    { *m = SessionsReply{} }
func (m *SessionsReply) String() string            { return proto.CompactTextString(m) }
func (*SessionsReply) ProtoMessage()               {}
func (*SessionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type TopicsRequest struct {
}

func (m *TopicsRequest) Reset()                    { *m = TopicsRequest{} }
func (m *TopicsRequest) String() string            { return proto.CompactTextString(m) }
func (*TopicsRequest) ProtoMessage()               {}
func (*TopicsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type TopicsReply struct {
}

func (m *TopicsReply) Reset()                    { *m = TopicsReply{} }
func (m *TopicsReply) String() string            { return proto.CompactTextString(m) }
func (*TopicsReply) ProtoMessage()               {}
func (*TopicsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func init() {
	proto.RegisterType((*VersionRequest)(nil), "api.VersionRequest")
	proto.RegisterType((*VersionReply)(nil), "api.VersionReply")
	proto.RegisterType((*BrokerRequest)(nil), "api.BrokerRequest")
	proto.RegisterType((*BrokerReply)(nil), "api.BrokerReply")
	proto.RegisterType((*ClientsRequest)(nil), "api.ClientsRequest")
	proto.RegisterType((*ClientsReply)(nil), "api.ClientsReply")
	proto.RegisterType((*ClientInfo)(nil), "api.ClientInfo")
	proto.RegisterType((*AdminsRequest)(nil), "api.AdminsRequest")
	proto.RegisterType((*AdminsReply)(nil), "api.AdminsReply")
	proto.RegisterType((*ClusterRequest)(nil), "api.ClusterRequest")
	proto.RegisterType((*ClusterReply)(nil), "api.ClusterReply")
	proto.RegisterType((*RoutesRequest)(nil), "api.RoutesRequest")
	proto.RegisterType((*RoutesReply)(nil), "api.RoutesReply")
	proto.RegisterType((*StatusRequest)(nil), "api.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "api.StatusReply")
	proto.RegisterType((*PluginsRequest)(nil), "api.PluginsRequest")
	proto.RegisterType((*PluginsReply)(nil), "api.PluginsReply")
	proto.RegisterType((*ServicesRequest)(nil), "api.ServicesRequest")
	proto.RegisterType((*ServicesReply)(nil), "api.ServicesReply")
	proto.RegisterType((*SubscriptionsRequest)(nil), "api.SubscriptionsRequest")
	proto.RegisterType((*SubscriptionsReply)(nil), "api.SubscriptionsReply")
	proto.RegisterType((*SessionsRequest)(nil), "api.SessionsRequest")
	proto.RegisterType((*SessionsReply)(nil), "api.SessionsReply")
	proto.RegisterType((*TopicsRequest)(nil), "api.TopicsRequest")
	proto.RegisterType((*TopicsReply)(nil), "api.TopicsReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Api service

type ApiClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error)
	Admins(ctx context.Context, in *AdminsRequest, opts ...grpc.CallOption) (*AdminsReply, error)
	Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterReply, error)
	Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesReply, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Broker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerReply, error)
	Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsReply, error)
	Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesReply, error)
	Subscriptions(ctx context.Context, in *SubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionsReply, error)
	Clients(ctx context.Context, in *ClientsRequest, opts ...grpc.CallOption) (*ClientsReply, error)
	Sessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsReply, error)
	Topics(ctx context.Context, in *TopicsRequest, opts ...grpc.CallOption) (*TopicsReply, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error) {
	out := new(VersionReply)
	err := grpc.Invoke(ctx, "/api.Api/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Admins(ctx context.Context, in *AdminsRequest, opts ...grpc.CallOption) (*AdminsReply, error) {
	out := new(AdminsReply)
	err := grpc.Invoke(ctx, "/api.Api/Admins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Cluster(ctx context.Context, in *ClusterRequest, opts ...grpc.CallOption) (*ClusterReply, error) {
	out := new(ClusterReply)
	err := grpc.Invoke(ctx, "/api.Api/Cluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Routes(ctx context.Context, in *RoutesRequest, opts ...grpc.CallOption) (*RoutesReply, error) {
	out := new(RoutesReply)
	err := grpc.Invoke(ctx, "/api.Api/Routes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	out := new(StatusReply)
	err := grpc.Invoke(ctx, "/api.Api/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Broker(ctx context.Context, in *BrokerRequest, opts ...grpc.CallOption) (*BrokerReply, error) {
	out := new(BrokerReply)
	err := grpc.Invoke(ctx, "/api.Api/Broker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Plugins(ctx context.Context, in *PluginsRequest, opts ...grpc.CallOption) (*PluginsReply, error) {
	out := new(PluginsReply)
	err := grpc.Invoke(ctx, "/api.Api/Plugins", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesReply, error) {
	out := new(ServicesReply)
	err := grpc.Invoke(ctx, "/api.Api/Services", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Subscriptions(ctx context.Context, in *SubscriptionsRequest, opts ...grpc.CallOption) (*SubscriptionsReply, error) {
	out := new(SubscriptionsReply)
	err := grpc.Invoke(ctx, "/api.Api/Subscriptions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Clients(ctx context.Context, in *ClientsRequest, opts ...grpc.CallOption) (*ClientsReply, error) {
	out := new(ClientsReply)
	err := grpc.Invoke(ctx, "/api.Api/Clients", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Sessions(ctx context.Context, in *SessionsRequest, opts ...grpc.CallOption) (*SessionsReply, error) {
	out := new(SessionsReply)
	err := grpc.Invoke(ctx, "/api.Api/Sessions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Topics(ctx context.Context, in *TopicsRequest, opts ...grpc.CallOption) (*TopicsReply, error) {
	out := new(TopicsReply)
	err := grpc.Invoke(ctx, "/api.Api/Topics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	Version(context.Context, *VersionRequest) (*VersionReply, error)
	Admins(context.Context, *AdminsRequest) (*AdminsReply, error)
	Cluster(context.Context, *ClusterRequest) (*ClusterReply, error)
	Routes(context.Context, *RoutesRequest) (*RoutesReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	Broker(context.Context, *BrokerRequest) (*BrokerReply, error)
	Plugins(context.Context, *PluginsRequest) (*PluginsReply, error)
	Services(context.Context, *ServicesRequest) (*ServicesReply, error)
	Subscriptions(context.Context, *SubscriptionsRequest) (*SubscriptionsReply, error)
	Clients(context.Context, *ClientsRequest) (*ClientsReply, error)
	Sessions(context.Context, *SessionsRequest) (*SessionsReply, error)
	Topics(context.Context, *TopicsRequest) (*TopicsReply, error)
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Admins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Admins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Admins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Admins(ctx, req.(*AdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Cluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Cluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Cluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Cluster(ctx, req.(*ClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Routes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Routes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Routes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Routes(ctx, req.(*RoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Broker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Broker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Broker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Broker(ctx, req.(*BrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Plugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Plugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Plugins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Plugins(ctx, req.(*PluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Services_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Services(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Services",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Services(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Subscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Subscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Subscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Subscriptions(ctx, req.(*SubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Clients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Clients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Clients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Clients(ctx, req.(*ClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Sessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Sessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Sessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Sessions(ctx, req.(*SessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Topics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Topics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Topics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Topics(ctx, req.(*TopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Api_Version_Handler,
		},
		{
			MethodName: "Admins",
			Handler:    _Api_Admins_Handler,
		},
		{
			MethodName: "Cluster",
			Handler:    _Api_Cluster_Handler,
		},
		{
			MethodName: "Routes",
			Handler:    _Api_Routes_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Api_Status_Handler,
		},
		{
			MethodName: "Broker",
			Handler:    _Api_Broker_Handler,
		},
		{
			MethodName: "Plugins",
			Handler:    _Api_Plugins_Handler,
		},
		{
			MethodName: "Services",
			Handler:    _Api_Services_Handler,
		},
		{
			MethodName: "Subscriptions",
			Handler:    _Api_Subscriptions_Handler,
		},
		{
			MethodName: "Clients",
			Handler:    _Api_Clients_Handler,
		},
		{
			MethodName: "Sessions",
			Handler:    _Api_Sessions_Handler,
		},
		{
			MethodName: "Topics",
			Handler:    _Api_Topics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0xe6, 0xa3, 0x93, 0xcf, 0x2e, 0x51, 0x31, 0x46, 0x48, 0xd1, 0x9e, 0x82, 0x90,
	0x22, 0x68, 0x24, 0xa8, 0x7a, 0x2b, 0x51, 0x25, 0x38, 0x80, 0x8a, 0x53, 0xb8, 0xbb, 0xe9, 0x52,
	0xad, 0xea, 0xd8, 0xc6, 0x5e, 0x57, 0xca, 0x5f, 0xe8, 0x9f, 0xe5, 0x2f, 0xa0, 0xdd, 0x9d, 0xdd,
	0xec, 0x96, 0x1e, 0xe0, 0xd6, 0x79, 0x33, 0x6f, 0x66, 0xf2, 0xe6, 0x79, 0x0b, 0x87, 0x49, 0xc1,
	0x17, 0x45, 0x99, 0x8b, 0x9c, 0xb4, 0x92, 0x82, 0xd3, 0x09, 0x8c, 0x7e, 0xb0, 0xb2, 0xe2, 0x79,
	0x16, 0xb3, 0x5f, 0x35, 0xab, 0x04, 0x9d, 0xc3, 0xc0, 0x22, 0x45, 0xba, 0x23, 0x21, 0x74, 0x31,
	0x0e, 0x83, 0x59, 0x30, 0x3f, 0x8c, 0x4d, 0x48, 0xdf, 0xc0, 0xf0, 0x63, 0x99, 0xdf, 0xb1, 0x12,
	0xa9, 0x24, 0x82, 0xde, 0x2a, 0x11, 0xec, 0x36, 0x2f, 0x77, 0x58, 0x6b, 0x63, 0xfa, 0x3b, 0x80,
	0xbe, 0xa9, 0x96, 0x6d, 0xdf, 0x41, 0x7b, 0x2d, 0x12, 0x51, 0x85, 0xc1, 0xac, 0x35, 0xef, 0x9f,
	0xbc, 0x5c, 0xc8, 0xc5, 0x9c, 0x82, 0x85, 0xca, 0x5e, 0x64, 0xa2, 0xdc, 0xc5, 0xba, 0x92, 0x7c,
	0x80, 0xee, 0x17, 0x26, 0x4a, 0xbe, 0xa9, 0xc2, 0xa6, 0x22, 0xbd, 0xfa, 0x8b, 0x84, 0x79, 0x4d,
	0x33, 0xd5, 0xd1, 0x29, 0xc0, 0xbe, 0x1b, 0x99, 0x40, 0xeb, 0x8e, 0x99, 0x05, 0xe5, 0x9f, 0x64,
	0x0a, 0xed, 0xfb, 0x24, 0xad, 0x59, 0xd8, 0x9c, 0x05, 0xf3, 0x83, 0x58, 0x07, 0x67, 0xcd, 0xd3,
	0x20, 0x3a, 0x83, 0x81, 0xdb, 0xf2, 0x7f, 0xb8, 0xf4, 0x13, 0x8c, 0x56, 0x29, 0x67, 0x99, 0xa8,
	0xfe, 0x41, 0x1f, 0x95, 0x53, 0xd5, 0x9f, 0x6f, 0x54, 0x2b, 0x99, 0xc3, 0x98, 0x7e, 0x83, 0x81,
	0xed, 0x24, 0xb5, 0x3b, 0x86, 0x4e, 0xcc, 0xaa, 0x3a, 0x15, 0xaa, 0x4b, 0x2f, 0xc6, 0x88, 0xbc,
	0x86, 0x2e, 0xd6, 0xa1, 0x40, 0x63, 0x25, 0x10, 0xf6, 0xc9, 0x7e, 0xe6, 0xb1, 0xc9, 0xd3, 0x87,
	0x00, 0x60, 0x8f, 0xcb, 0xe9, 0xdf, 0x2b, 0x56, 0x7e, 0x4d, 0xb6, 0xcc, 0x6c, 0x66, 0x62, 0x42,
	0xe5, 0x74, 0x96, 0x64, 0x6b, 0x56, 0x29, 0x17, 0x34, 0xd5, 0x4c, 0x0f, 0x93, 0xfc, 0x4b, 0x86,
	0xfc, 0x96, 0xe6, 0x9b, 0x98, 0xcc, 0xa0, 0xbf, 0xca, 0xb3, 0x8c, 0x6d, 0xc4, 0x15, 0xdf, 0xb2,
	0xf0, 0x40, 0xa5, 0x5d, 0x88, 0x8e, 0x61, 0x78, 0x7e, 0xb3, 0xe5, 0x99, 0x11, 0x8a, 0x0e, 0xa1,
	0x6f, 0x80, 0x22, 0xdd, 0x49, 0x93, 0xae, 0xd2, 0xba, 0x12, 0xd6, 0x69, 0x74, 0x24, 0x77, 0x42,
	0x44, 0x56, 0x8c, 0x61, 0x18, 0xe7, 0xb5, 0x60, 0x6e, 0x07, 0x03, 0x60, 0x5e, 0x3a, 0xa0, 0x76,
	0xf3, 0x06, 0xc0, 0x09, 0x97, 0x69, 0x7d, 0xeb, 0xac, 0x30, 0x82, 0x81, 0x45, 0x64, 0xc5, 0x11,
	0x8c, 0xd7, 0xac, 0xbc, 0xe7, 0x9b, 0xfd, 0x0c, 0xd9, 0xd4, 0x42, 0xb2, 0xe6, 0x18, 0xa6, 0xeb,
	0xfa, 0xba, 0xda, 0x94, 0xbc, 0x10, 0x3c, 0xdf, 0xf7, 0x9a, 0x02, 0x79, 0x84, 0xdb, 0x8e, 0x4a,
	0x3e, 0xbf, 0xa3, 0x81, 0x70, 0xef, 0xab, 0xbc, 0xe0, 0x1b, 0x77, 0x6f, 0x03, 0x14, 0xe9, 0xee,
	0xe4, 0xa1, 0x0d, 0xad, 0xf3, 0x82, 0x93, 0xa5, 0xfd, 0x48, 0xc9, 0x33, 0x75, 0x73, 0xff, 0xa3,
	0x8e, 0x8e, 0x7c, 0x50, 0xb6, 0x6e, 0x90, 0xb7, 0xd0, 0xd1, 0x2a, 0x13, 0xa2, 0xd2, 0xde, 0x0d,
	0xa2, 0x89, 0x87, 0x69, 0xc6, 0x52, 0x1a, 0x4c, 0xc9, 0x8e, 0x63, 0xfc, 0xb3, 0xe0, 0x18, 0xef,
	0x32, 0x6a, 0x8c, 0x3e, 0x05, 0x8e, 0xf1, 0x0e, 0x85, 0x63, 0xdc, 0x5b, 0x29, 0x86, 0x3e, 0x0e,
	0x32, 0xbc, 0xd3, 0x21, 0xc3, 0xbd, 0x9e, 0x62, 0xe8, 0x67, 0x00, 0x19, 0xde, 0xbb, 0x84, 0x0c,
	0xe7, 0x9d, 0xd0, 0x3f, 0x05, 0xef, 0x8b, 0x3f, 0xc5, 0xbf, 0x3f, 0xfe, 0x14, 0xcf, 0x02, 0x0d,
	0xf2, 0x1e, 0x7a, 0xe6, 0xe2, 0x64, 0xaa, 0xd7, 0xf0, 0x3d, 0x11, 0x91, 0x47, 0xa8, 0xe6, 0x5d,
	0xc0, 0xd0, 0x33, 0x00, 0x79, 0xa1, 0xcb, 0x9e, 0x30, 0x4b, 0xf4, 0xfc, 0xa9, 0x94, 0x23, 0xbf,
	0xfa, 0x7e, 0xad, 0xfc, 0xee, 0xfb, 0x62, 0xe5, 0xdf, 0x3f, 0x15, 0x66, 0x67, 0xed, 0x29, 0xbb,
	0xb3, 0xe7, 0x3a, 0xbb, 0xb3, 0x6b, 0x3c, 0x25, 0xa9, 0x76, 0x1a, 0x4a, 0xea, 0xf9, 0x10, 0x25,
	0x75, 0xac, 0x48, 0x1b, 0xd7, 0x1d, 0xf5, 0x7f, 0x65, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0xa1,
	0xef, 0xef, 0x9e, 0x64, 0x06, 0x00, 0x00,
}
