// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	AuthRequest
	AuthReply
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Clientid string `protobuf:"bytes,1,opt,name=clientid" json:"clientid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Topic    string `protobuf:"bytes,4,opt,name=topic" json:"topic,omitempty"`
	Hint     string `protobuf:"bytes,5,opt,name=hint" json:"hint,omitempty"`
	Access   string `protobuf:"bytes,6,opt,name=access" json:"access,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetClientid() string {
	if m != nil {
		return m.Clientid
	}
	return ""
}

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *AuthRequest) GetHint() string {
	if m != nil {
		return m.Hint
	}
	return ""
}

func (m *AuthRequest) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

type AuthReply struct {
	Result  bool   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *AuthReply) Reset()                    { *m = AuthReply{} }
func (m *AuthReply) String() string            { return proto.CompactTextString(m) }
func (*AuthReply) ProtoMessage()               {}
func (*AuthReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *AuthReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AuthReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "auth.AuthRequest")
	proto.RegisterType((*AuthReply)(nil), "auth.AuthReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	// Get version of Authlet service
	GetVersion(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error)
	// Check acl based on client id, user name and topic
	CheckAcl(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error)
	// Check user name and password
	CheckUserNameAndPassword(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error)
	// Get PSK key
	GetPskKey(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetVersion(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error) {
	out := new(AuthReply)
	err := grpc.Invoke(ctx, "/auth.AuthService/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckAcl(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error) {
	out := new(AuthReply)
	err := grpc.Invoke(ctx, "/auth.AuthService/CheckAcl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckUserNameAndPassword(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error) {
	out := new(AuthReply)
	err := grpc.Invoke(ctx, "/auth.AuthService/CheckUserNameAndPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetPskKey(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthReply, error) {
	out := new(AuthReply)
	err := grpc.Invoke(ctx, "/auth.AuthService/GetPskKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	// Get version of Authlet service
	GetVersion(context.Context, *AuthRequest) (*AuthReply, error)
	// Check acl based on client id, user name and topic
	CheckAcl(context.Context, *AuthRequest) (*AuthReply, error)
	// Check user name and password
	CheckUserNameAndPassword(context.Context, *AuthRequest) (*AuthReply, error)
	// Get PSK key
	GetPskKey(context.Context, *AuthRequest) (*AuthReply, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetVersion(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/CheckAcl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckAcl(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckUserNameAndPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckUserNameAndPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/CheckUserNameAndPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckUserNameAndPassword(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetPskKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetPskKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/GetPskKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetPskKey(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AuthService_GetVersion_Handler,
		},
		{
			MethodName: "CheckAcl",
			Handler:    _AuthService_CheckAcl_Handler,
		},
		{
			MethodName: "CheckUserNameAndPassword",
			Handler:    _AuthService_CheckUserNameAndPassword_Handler,
		},
		{
			MethodName: "GetPskKey",
			Handler:    _AuthService_GetPskKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4e, 0xb4, 0x30,
	0x10, 0xc7, 0x3f, 0xbe, 0x65, 0x11, 0xc6, 0x83, 0x3a, 0x31, 0xa6, 0xd9, 0x93, 0xe1, 0xe4, 0x69,
	0xa3, 0xeb, 0x0b, 0x48, 0x3c, 0xec, 0xc1, 0x44, 0x37, 0x18, 0xbd, 0x63, 0x99, 0x84, 0x06, 0x16,
	0xb0, 0x1d, 0xd6, 0xf0, 0x3c, 0xbe, 0x9c, 0x8f, 0x61, 0x28, 0xc5, 0xec, 0x91, 0xdb, 0xfc, 0xe6,
	0xd7, 0x69, 0xfe, 0x9d, 0x02, 0x64, 0x1d, 0x17, 0xeb, 0x56, 0x37, 0xdc, 0xa0, 0x3f, 0xd4, 0xf1,
	0xb7, 0x07, 0xa7, 0x49, 0xc7, 0x45, 0x4a, 0x9f, 0x1d, 0x19, 0xc6, 0x15, 0x84, 0xb2, 0x52, 0x54,
	0xb3, 0xca, 0x85, 0x77, 0xed, 0xdd, 0x44, 0xe9, 0x1f, 0x0f, 0xae, 0x33, 0xa4, 0xeb, 0x6c, 0x4f,
	0xe2, 0xff, 0xe8, 0x26, 0x1e, 0x5c, 0x9b, 0x19, 0xf3, 0xd5, 0xe8, 0x5c, 0x2c, 0x46, 0x37, 0x31,
	0x5e, 0xc2, 0x92, 0x9b, 0x56, 0x49, 0xe1, 0x5b, 0x31, 0x02, 0x22, 0xf8, 0x85, 0xaa, 0x59, 0x2c,
	0x6d, 0xd3, 0xd6, 0x78, 0x05, 0x41, 0x26, 0x25, 0x19, 0x23, 0x02, 0xdb, 0x75, 0x14, 0xbf, 0x40,
	0x34, 0x86, 0x6c, 0xab, 0x7e, 0x38, 0xa4, 0xc9, 0x74, 0x15, 0xdb, 0x80, 0x61, 0xea, 0x08, 0xcf,
	0x61, 0x51, 0x52, 0xef, 0x92, 0x0d, 0x25, 0x0a, 0x38, 0x39, 0x90, 0x36, 0xaa, 0xa9, 0x5d, 0xa6,
	0x09, 0x37, 0x3f, 0xee, 0xd9, 0xaf, 0xa4, 0x0f, 0x4a, 0x12, 0x6e, 0x00, 0xb6, 0xc4, 0xef, 0xa3,
	0xc5, 0x8b, 0xb5, 0xdd, 0xd3, 0xd1, 0x5e, 0x56, 0x67, 0xc7, 0xad, 0xb6, 0xea, 0xe3, 0x7f, 0x78,
	0x0b, 0xe1, 0x63, 0x41, 0xb2, 0x4c, 0x64, 0x35, 0x73, 0xe2, 0x01, 0x84, 0x9d, 0x78, 0x33, 0xa4,
	0x9f, 0xb3, 0x3d, 0x25, 0x75, 0xbe, 0x9b, 0x96, 0x34, 0xef, 0x86, 0x3b, 0x88, 0xb6, 0xc4, 0x3b,
	0x53, 0x3e, 0x51, 0x3f, 0x6f, 0xe4, 0x23, 0xb0, 0xdf, 0x7d, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x3e, 0xee, 0xfd, 0xc4, 0xfc, 0x01, 0x00, 0x00,
}
